SchoolWebSite2/SchoolWebSite2/Models/Person.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronimic { get; set; }
        public string HomeNumber { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string Photo { get; set; }
        public string Info { get; set; }
        public string Role { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}

SchoolWebSite2/SchoolWebSite2/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolWebSite2.Models;

namespace SchoolWebSite2.Controllers
{
    public class PeopleController : Controller
    {
        public ActionResult Index(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var person = db.Person.FirstOrDefault(p => p.Id == id);
            if(person == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(person);
        }

        public ActionResult Edit(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var person = db.Person.FirstOrDefault(p => p.Id == id);
            if (person == null)
            {
                return RedirectToAction("NotFound", "Error");
            }
            return View(person);
        }

        [HttpPost]
        public ActionResult Edit(Person person, HttpPostedFileBase upload)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            if (upload != null && upload.ContentLength > 0)
            {
                if (string.IsNullOrEmpty(person.Photo))
                {
                    person.Photo = @"~/Images/" + upload.FileName;
                }
            }

            ModelState.Remove("Role");
            ModelState.Remove("Password");
            ModelState.Remove("Login");
            if (ModelState.IsValid)
            {
                var dbPerson = db.Person.FirstOrDefault(p => p.Id == person.Id);
                if (dbPerson != null)
                {
                    dbPerson.Address = person.Address;
                    dbPerson.BirthDate = person.BirthDate;
                    dbPerson.Email = person.Email;
                    dbPerson.HomeNumber = person.HomeNumber;
                    dbPerson.Info = person.Info;
                    dbPerson.MobileNumber = person.MobileNumber;
                    dbPerson.Name = person.Name;
                    dbPerson.Patronimic = person.Patronimic;
                    dbPerson.Photo = person.Photo;
                    dbPerson.Surname = person.Surname;
                    dbPerson.Login = "111111111";
                    dbPerson.Password = "111111111";
                    db.SaveChanges();
                }

                if(dbPerson.Role == "Учитель")
                {
                    return RedirectToAction("Index", "Teachers");
                }
                else
                {
                    return RedirectToAction("Index", "Students");
                }
                
            }

            return View(person);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            bool isTeacher = false;
            var authDB = new ApplicationDbContext();
            var db = new SchoolWebsiteDatabaseEntities();
            var dbPerson = db.Person.FirstOrDefault(p => p.Id == id);
            if (dbPerson != null)
            {
                isTeacher = dbPerson.Role == "Учитель";
                var userName = db.User.FirstOrDefault(u => u.PersonId == id).Login;
                db.Person.Remove(dbPerson);
                db.SaveChanges();

                var authUser = authDB.Users.FirstOrDefault(u => u.UserName == userName);
                authDB.Users.Remove(authUser);
                authDB.SaveChanges();
            }
                
            if (isTeacher)
            {
                return RedirectToAction("Index", "Teachers");
            }
            else
            {
                return RedirectToAction("Index", "Students");
            }
        }
    }
}

SchoolWebSite2/SchoolWebSite2/Views/People/Edit.cshtml
@model SchoolWebSite2.Models.Person

@functions{
    string GetSrc()
    {
        if (string.IsNullOrEmpty(Model.Photo))
        {
            return Url.Content("~/Images/userdefault.jpg");
        }
        else
        {
            return Url.Content(Model.Photo);
        }
    }

    string GetCorectDate()
    {
        if (Model.BirthDate == null)
        {
            return null;
        }

        string day = Model.BirthDate.Value.Day.ToString();
        if (day.Length == 1)
        {
            day = "0" + day;
        }
        string month = Model.BirthDate.Value.Month.ToString();
        if (month.Length == 1)
        {
            month = "0" + month;
        }

        return Model.BirthDate.Value.Year.ToString() + "-" + month + "-" + day;
    }
}

<style>

    .main-part {
        margin: 2% 15%;
        text-align: center;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    .photo-part {
        width: 30%;
        text-align: center;
    }

    .right-from-photo-part {
        margin-left: 8%;
        width: 60%;
    }

    .rest-part {
        width: 100%;
    }

    label, .input-font-size {
        font-size: 20px;
    }
</style>


    <div class="main-part">
        <h2>Редактирование</h2>

        @using (Html.BeginForm("Edit", "People", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Photo)
            <div class="form-horizontal main-container">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="photo-part">
                    <div class="form-group">
                        <div class="col-md-10">
                            <input type="file" id="inputFile" name="upload" style="display: unset;width:auto;" class="input-font-size" />
                            <img style="width:200px;height:250px" id="targetPhoto" src="@GetSrc()" />
                        </div>
                    </div>
                </div>
                <div class="right-from-photo-part">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Patronimic, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Patronimic, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.Patronimic, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input class="form-control input-font-size text-box single-line" data-val="true" data-val-date="Поле Дата рождения должно содержать дату."
                                   id="BirthDate" name="BirthDate" type="date" value="@GetCorectDate()">

                            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="rest-part">
                    <div class="form-group">
                        @Html.LabelFor(model => model.HomeNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HomeNumber, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.HomeNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.MobileNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control input-font-size" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Info, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">

                            @Html.TextAreaFor(model => model.Info, 5, 10, new { @class = "form-control input-font-size" })
                            @Html.ValidationMessageFor(model => model.Info, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Сохранить" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

<script>
    $(function () {
        $("#inputFile").change(function () {
            readURL(this);
        });
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#targetPhoto').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

SchoolWebSite2/SchoolWebSite2/Views/People/Index.cshtml
@model SchoolWebSite2.Models.Person

@functions{
    string GetSrc()
    {
        if (string.IsNullOrEmpty(Model.Photo))
        {
            return Url.Content("~/Images/userdefault.jpg");
        }
        else
        {
            return Url.Content(Model.Photo);
        }
    }
}

<style>
    .main-part {
        margin: 2% 15%;
        text-align: center;
        font-size: 20px;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    .photo-part {
        width: 30%;
        text-align: center;
    }

    .right-from-photo-part {
        width: 70%;
    }

    .rest-part {
        width: 100%;
    }

    .float-unset {
        float: unset;
    }

    .float-left {
        float: left;
    }

    .control-label{
        padding-top: 0;
    }

    label{
        font-size:20px;
        text-align: left;
    }

    .words-wrapped{
        word-break: break-word;
    }
</style>

    <div class="main-part">
        @Html.AntiForgeryToken()
        <div class="form-horizontal main-container">
            <hr />
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="photo-part">
                <div class="form-group">
                    <div class="col-md-10">
                        <img style="width:200px;height:250px" id="targetPhoto" src="@GetSrc()" />
                    </div>
                </div>
            </div>
            <div class="right-from-photo-part">
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.DisplayFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control float-unset" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-md-4" })
                    <div class="col-md-5">
                        @Html.DisplayFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "col-md-4" })
                    <div class="col-md-5">
                        @Html.DisplayFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.HomeNumber, htmlAttributes: new { @class = "col-md-4" })
                    <div class="col-md-5">
                        @Html.DisplayFor(model => model.HomeNumber, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.MobileNumber, htmlAttributes: new { @class = "col-md-4" })
                    <div class="col-md-5">
                        @Html.DisplayFor(model => model.MobileNumber, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = " col-md-4" })
                    <div class="col-md-5">
                        @Html.DisplayFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="rest-part">
                <div class="form-group">
                    @Html.LabelFor(model => model.Info, htmlAttributes: new { @class = "col-md-2" })
                    <div class="col-md-10 words-wrapped">
                        @Html.DisplayFor(model => model.Info, new { @class = "form-control" })
                    </div>
                </div>
            </div>
        </div>
    </div>