SchoolWebSite2/SchoolWebSite2/Models/Teacher.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int PersonId { get; set; }
        public Nullable<int> TeacherLoad { get; set; }
    
        public virtual Person Person { get; set; }
    }
}

SchoolWebSite2/SchoolWebSite2/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolWebSite2.Models;
using PagedList;
using PagedList.Mvc;

namespace SchoolWebSite2.Controllers
{
    public class TeachersController : Controller
    {
        public ActionResult Index(string search, int? page)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var teachers = db.Person.Where(p => p.Role == "Учитель");
            if (!string.IsNullOrEmpty(search))
            {
                teachers = teachers.Where(p => p.Name.Contains(search) || p.Surname.Contains(search) || p.Patronimic.Contains(search));
            }
            var result = teachers.OrderBy(p => p.Surname).ToList().ToPagedList(page ?? 1, 3);
            return View(result);
        }

        public ActionResult IndexForAdmin()
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var teachers = db.Teacher.OrderBy(t => t.Person.Surname).ToList();
            return View(teachers);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var teacherToEdit = db.Teacher.First(t => t.PersonId == id);
            var subjects = db.Subject.Select(s => s).ToList();
            RemoveUnneccessarySubject(subjects, teacherToEdit);
            ViewBag.Subjects = new SelectList(subjects, "Id", "FullName");
            var teacherSubjects = teacherToEdit.Subject.OrderBy(s => s.FullName).ToList();
            return View(new TeacherWithSubjectsModel() { Subjects = teacherSubjects, Teacher = teacherToEdit});
        }

        [HttpPost]
        public ActionResult Edit(TeacherWithSubjectsModel model)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            if (ModelState.IsValid)
            {
                var teacherToEdit = db.Teacher.First(t => t.PersonId == model.Teacher.PersonId);
                if (teacherToEdit != null)
                {
                    teacherToEdit.TeacherLoad = model.Teacher.TeacherLoad;
                }
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = model.Teacher.PersonId });
            }
            var teacher = db.Teacher.First(t => t.PersonId == model.Teacher.PersonId);
            var subjects = db.Subject.Select(s => s).ToList();
            RemoveUnneccessarySubject(subjects, teacher);
            ViewBag.Subjects = new SelectList(subjects, "Id", "FullName");
            model.Teacher = teacher;
            model.Subjects = teacher.Subject.OrderBy(s => s.FullName).ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult AddSubject(TeacherWithSubjectsModel model)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            if (model.NewSubjectId == null)
            {
                ModelState.AddModelError(string.Empty, "Выберите предмет из списка!");
            }

            ModelState.Remove("Teacher.TeacherLoad");
            if (ModelState.IsValid)
            {
                var teacher = db.Teacher.First(t => t.PersonId == model.Teacher.PersonId);
                var subject = db.Subject.First(s => s.Id == model.NewSubjectId);
                if (teacher != null)
                {
                    teacher.Subject.Add(subject);
                }
                db.SaveChanges();
            }

            return RedirectToAction("Edit", new { id = model.Teacher.PersonId });
        }

        [HttpPost]
        public ActionResult RemoveSubject(int subjectId, int teacherId)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var teacher = db.Teacher.First(t => t.PersonId == teacherId);
            var subject = db.Subject.First(s => s.Id == subjectId);
            if (teacher != null)
            {
                teacher.Subject.Remove(subject);
            }
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = teacherId });
        }

        private void RemoveUnneccessarySubject(List<Subject> list, Teacher teacher)
        {
            foreach(var subject in teacher.Subject)
            {
                list.Remove(subject);
            }
        }
    }
}

SchoolWebSite2/SchoolWebSite2/Views/Teachers/Edit.cshtml
@model SchoolWebSite2.Models.TeacherWithSubjectsModel

<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>@Model.Teacher.FullName</h2>
        @Html.AntiForgeryToken()

        @using (Html.BeginForm("Edit", "Teachers", null, FormMethod.Post))
        {
            <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;">
                @Html.HiddenFor(model => model.Teacher.PersonId)
                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.Teacher.TeacherLoad, htmlAttributes: new { @class = "" })
                    @Html.EditorFor(model => model.Teacher.TeacherLoad, new { htmlAttributes = new { @class = "form-control code-input", @min = "1", @max = "100" } })
                </div>
                <input type="submit" value="Сохранить" class="btn btn-default" style="margin:10px 0;" />
            </div>
            @Html.ValidationMessageFor(model => model.Teacher.TeacherLoad, "", new { @class = "text-danger" })
        }

        <h2>Добавление предмета</h2>

        @using (Html.BeginForm("AddSubject", "Teachers", null, FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Teacher.PersonId)
            <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;">
                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.NewSubjectId, htmlAttributes: new { @class = "" })
                    @Html.DropDownListFor(model => model.NewSubjectId, (SelectList)ViewBag.Subjects, "Выберите новый предмет", new { @class = "form-control input-font-size class-teacher-input", @style = "height:auto;" })
                </div>
                <input type="submit" value="Добавить" class="btn btn-default" style="margin:10px 0;" />
            </div>
            @Html.ValidationMessageFor(model => model.NewSubjectId, "", new { @class = "text-danger" })
        }

        <h2>Список предметов преподавателя</h2>

        <div class="form-horizontal main-container">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="main-content">
                @for (int i = 0; i < Model.Subjects.Count(); i++)
                {
                    <div style="display:flex;flex-direction:row;width:400px;">
                        <div style="margin:10px 0;"> @Model.Subjects[i].FullName </div>
                        @using (Html.BeginForm("RemoveSubject", "Teachers", new { subjectId = Model.Subjects[i].Id, teacherId = Model.Teacher.PersonId }, FormMethod.Post))
                        {
                            <input type="submit" value="Удалить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SchoolWebSite2/SchoolWebSite2/Views/Teachers/Index.cshtml
@using PagedList;
@using PagedList.Mvc;

@model IEnumerable<SchoolWebSite2.Models.Person>

<style>
    .person-container {
        display: flex;
        background-color: #ddf1f1;
        flex-direction: column;
        margin: 0 15%;
    }

    .search-box {
        display: flex;
        justify-content: center;
        margin-top: 30px;
    }

    .input-font-size {
        font-size: 20px;
        width: 350px;
        margin-right: 30px;
    }
</style>

<div class="person-container">

    @using (Html.BeginForm("Index", "Teachers", FormMethod.Get))
    {
        <div class="search-box">
            @Html.TextBox("Search", "", new { @class = "form-control input-font-size" })
            <input type="submit" value="Найти" class="btn btn-default" />
        </div>
    }

    @foreach (var person in Model)
    {
        Html.RenderPartial("PersonShortInfo", person);
    }
    
    <div class="search-box">
         @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
    </div>
</div>

SchoolWebSite2/SchoolWebSite2/Views/Teachers/IndexForAdmin.cshtml
@model IEnumerable<SchoolWebSite2.Models.Teacher>


<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 0 0 15%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>Редактирование преподавателей</h2>
        @Html.AntiForgeryToken()
        <div class="form-horizontal main-container">
            <div class="main-content">
                @foreach (var teacher in Model)
                {
                    <div style="display:flex;flex-direction:row;width:600px;">
                        <div style="margin:10px 0;"> @teacher.FullName </div>
                        <div style="margin-left:auto;">
                            @using (Html.BeginForm("Edit", "Teachers", new { id = teacher.PersonId }, FormMethod.Get))
                            {
                                <input type="submit" value="Изменить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                            }
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>