SchoolWebSite2/SchoolWebSite2/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SchoolWebSite2.Models;

namespace SchoolWebSite2.Controllers
{
    public class ClassesController : Controller
    {
        public ActionResult Index()
        {
            var db = new SchoolWebsiteDatabaseEntities();
            ViewBag.Teachers = new SelectList(db.Teacher, "PersonId", "FullName");
            var list = db.Class.Select(c => c).OrderBy(c => c.Number).ThenBy(c => c.Code).ToList();
            return View(new CreateAndListClassModel() { Classes = list, NewClass = new Class() });
        }

        [HttpPost]
        public ActionResult Create(CreateAndListClassModel model)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            model.NewClass.Code = (model.NewClass.Code != null) ? model.NewClass.Code.Trim() : null;

            if (!db.IsClassUnique(model.NewClass))
            {
                ModelState.AddModelError(string.Empty, "Класс с таким номером и кодом уже существует!");
            }

            if (ModelState.IsValid)
            {
                db.Class.Add(model.NewClass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var list = db.Class.Select(c => c).OrderBy(c => c.Number).ThenBy(c => c.Code).ToList();
            ViewBag.Teachers = new SelectList(db.Teacher, "PersonId", "FullName");
            return View("Index", new CreateAndListClassModel() { Classes = list, NewClass = model.NewClass });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classToRemove = db.Class.FirstOrDefault(s => s.Id == id);
            db.Class.Remove(classToRemove);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classToEdit = db.Class.First(c => c.Id == id);
            ViewBag.Teachers = new SelectList(db.Teacher, "PersonId", "FullName", classToEdit.ClassTeacher);
            ViewBag.Students = new SelectList(db.Student.Where(s => s.Class == null), "PersonId", "FullName");
            var studentsInClass = db.Student.Where(s => s.Class.HasValue && s.Class == id).ToList();
            return View(new ClassWithStudentsModel() { Class = classToEdit, Students = studentsInClass});
        }

        [HttpPost]
        public ActionResult Edit(ClassWithStudentsModel model)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            model.Class.Code = (model.Class.Code != null) ? model.Class.Code.Trim() : null;

            if (!db.IsClassUnique(model.Class))
            {
                ModelState.AddModelError(string.Empty, "Класс с таким номером и кодом уже существует!");
            }

            if (ModelState.IsValid)
            {
                var classToEdit = db.Class.First(c => c.Id == model.Class.Id);
                if(classToEdit != null)
                {
                    classToEdit.Code = model.Class.Code;
                    classToEdit.Info = model.Class.Info;
                    classToEdit.ClassTeacher = model.Class.ClassTeacher;
                }
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = model.Class.Id });
            }
            var cl = db.Class.First(c => c.Id == model.Class.Id);
            ViewBag.Teachers = new SelectList(db.Teacher, "PersonId", "FullName", cl.ClassTeacher);
            ViewBag.Students = new SelectList(db.Student.Where(s => s.Class == null), "PersonId", "FullName");
            if(model.Students == null)
            {
                model.Students = new List<Student>();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult AddStudent(ClassWithStudentsModel model)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            if (model.NewStudentId == null)
            {
                ModelState.AddModelError(string.Empty, "Выберите ученика из списка!");
            }

            ModelState.Remove("Class.Code");
            ModelState.Remove("Class.Number");
            if (ModelState.IsValid)
            {
                var studentToEdit = db.Student.First(s => s.PersonId == model.NewStudentId);
                if (studentToEdit != null)
                {
                    studentToEdit.Class = model.Class.Id;
                }
                db.SaveChanges();
            }

            return RedirectToAction("Edit", new { id = model.Class.Id });
        }

        [HttpPost]
        public ActionResult RemoveStudent(int studentId, int classId)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var studentToRemove = db.Student.First(s => s.PersonId == studentId);
            if(studentToRemove != null)
            {
                studentToRemove.Class = null;
            }
            db.SaveChanges();
            return RedirectToAction("Edit", new { id = classId });
        }

        [HttpPost]
        public ActionResult IncrementYear()
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classList = db.Class.OrderByDescending(c => c.Number).ToList();
            for(int i = 0; i < classList.Count(); i++)
            {
                if(classList[i].Number == 11)
                {
                    db.Class.Remove(classList[i]);
                }
                else
                {
                    classList[i].Number++;
                }
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var students = db.Student.Where(s => s.Class.HasValue && s.Class == id).ToList();
            var classToShow = db.Class.First(c => c.Id == id);
            if (classToShow.ClassTeacher == null)
            {
                classToShow.ClassTeacherName = "Не выбран";
            }
            else
            {
                var teacher = db.Teacher.First(t => t.PersonId == classToShow.ClassTeacher);
                classToShow.ClassTeacherName = teacher.FullName;
            } 

            return View(new ClassWithStudentsModel() { Class = classToShow, Students = students });
        }

        [HttpGet]
        public ActionResult List()
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classes = db.Class.Select(c => c).OrderBy(c => c.Number).ThenBy(c => c.Code).ToList();
            return View(classes);
        }
    }
}

SchoolWebSite2/SchoolWebSite2/Views/Classes/Details.cshtml
@model SchoolWebSite2.Models.ClassWithStudentsModel

<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>@Model.Class.FullName</h2>
        @Html.AntiForgeryToken()
        <div style="display:flex;flex-direction:column;width:100%;flex-wrap:wrap;justify-content:center;">
            @Html.LabelFor(model => model.Class.ClassTeacher, htmlAttributes: new { @class = "" })
            <div style="font-size: 20px;margin: 20px 0;">@Html.DisplayFor(model => model.Class.ClassTeacherName)</div>
            @Html.LabelFor(model => model.Class.Info, htmlAttributes: new { @class = "" })
            <div style="font-size: 20px;margin: 20px 0;"> @Html.DisplayFor(model => model.Class.Info)</div>
        </div>
        <div class="form-horizontal main-container">
            <div class="main-content">
                @for (int i = 0; i < Model.Students.Count(); i++)
                {
                    <div style="display:flex;flex-direction:row;width:400px;">
                        <div style="margin:10px 0;"> @Html.DisplayFor(model =>  model.Students[i].FullName) </div>
                        
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SchoolWebSite2/SchoolWebSite2/Views/Classes/Edit.cshtml
@model SchoolWebSite2.Models.ClassWithStudentsModel

<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>@Model.Class.FullName</h2>
        @Html.AntiForgeryToken()

        @using (Html.BeginForm("Edit", "Classes", new { id = Model.Class.Id }, FormMethod.Post))
        {
            <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;">
                @Html.HiddenFor(model => model.Class.Number)
                @Html.HiddenFor(model => model.Class.Id)
                @Html.LabelFor(model => model.Class.Code, htmlAttributes: new { @class = "" })
                @Html.EditorFor(model => model.Class.Code, new { htmlAttributes = new { @class = "form-control code-input" } })

                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.Class.ClassTeacher, htmlAttributes: new { @class = "" })
                    @Html.DropDownListFor(model => model.Class.ClassTeacher, (SelectList)ViewBag.Teachers, "Выберите классного руководителя", new { @class = "form-control input-font-size class-teacher-input", @style = "height:auto;" })
                </div>
                @Html.LabelFor(model => model.Class.Info, htmlAttributes: new { @class = "" })
                @Html.TextAreaFor(model => model.Class.Info, 5, 10, new { @class = "form-control input-font-size" })
                <input type="submit" value="Сохранить" class="btn btn-default" style="margin:10px 0;" />
            </div>
            @Html.ValidationMessageFor(model => model.Class.Code, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.Class.ClassTeacher, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.Class.Info, "", new { @class = "text-danger" })
        }

        <h2>Добавление ученика</h2>

        @using (Html.BeginForm("AddStudent", "Classes", null, FormMethod.Post))
        {
            @Html.HiddenFor(model => model.Class.Id)
            <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;">
                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.NewStudentId, htmlAttributes: new { @class = "" })
                    @Html.DropDownListFor(model => model.NewStudentId, (SelectList)ViewBag.Students, "Выберите нового ученика", new { @class = "form-control input-font-size class-teacher-input", @style = "height:auto;" })
                </div>
                <input type="submit" value="Добавить" class="btn btn-default" style="margin:10px 0;" />
            </div>
            @Html.ValidationMessageFor(model => model.NewStudentId, "", new { @class = "text-danger" })
        }

        <h2>Список класса</h2>

        <div class="form-horizontal main-container">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="main-content">
                @for (int i = 0; i < Model.Students.Count(); i++)
                {
                    <div style="display:flex;flex-direction:row;width:400px;">
                        <div style="margin:10px 0;"> @Model.Students[i].FullName </div>
                        @using (Html.BeginForm("RemoveStudent", "Classes", new { studentId = Model.Students[i].PersonId, classId = Model.Class.Id }, FormMethod.Post))
                        {
                            <input type="submit" value="Удалить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SchoolWebSite2/SchoolWebSite2/Views/Classes/Index.cshtml
@model SchoolWebSite2.Models.CreateAndListClassModel

<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <div>
            <h2>Редактирование классов</h2>
            @using (Html.BeginForm("IncrementYear", "Classes", FormMethod.Post, new { Id = "incrementyearform" }))
            {
                <input id="IncrementYear" name="Common" type="button" value="Увеличить год" class="btn btn-default" style="float:right;" />
            }
        </div>
        @Html.AntiForgeryToken()

        @using (Html.BeginForm("Create", "Classes", null, FormMethod.Post))
        {
            <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;">
                @Html.LabelFor(model => model.NewClass.Number, htmlAttributes: new { @class = "" })
                @Html.EditorFor(model => model.NewClass.Number, new { htmlAttributes = new { @class = "form-control number-input", @min = "1", @max = "11" } })
                @Html.LabelFor(model => model.NewClass.Code, htmlAttributes: new { @class = "" })
                @Html.EditorFor(model => model.NewClass.Code, new { htmlAttributes = new { @class = "form-control code-input" } })

                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.NewClass.ClassTeacher, htmlAttributes: new { @class = "" })
                    @Html.DropDownListFor(model => model.NewClass.ClassTeacher, (SelectList)ViewBag.Teachers, "Выберите классного руководителя", new { @class = "form-control input-font-size class-teacher-input", @style = "height:auto;" })
                </div>
                @Html.LabelFor(model => model.NewClass.Info, htmlAttributes: new { @class = "" })
                @Html.TextAreaFor(model => model.NewClass.Info, 5, 10, new { @class = "form-control input-font-size" })
                <input type="submit" value="Добавить" class="btn btn-default" style="margin:10px 0;" />
            </div>
            @Html.ValidationMessageFor(model => model.NewClass.Number, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.NewClass.Code, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.NewClass.ClassTeacher, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.NewClass.Info, "", new { @class = "text-danger" })
        }

        <div class="form-horizontal main-container">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="main-content">
                @for (int i = 0; i < Model.Classes.Count(); i++)
                {
                    <div style="display:flex;flex-direction:row;width:400px;">
                        <div style="margin:10px 0;"> @Html.DisplayFor(model => model.Classes[i].FullName) </div>
                        @using (Html.BeginForm("Edit", "Classes", new { id = Model.Classes[i].Id }, FormMethod.Get))
                        {
                            <input type="submit" value="Изменить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                        @using (Html.BeginForm("Details", "Classes", new { id = Model.Classes[i].Id }, FormMethod.Get))
                        {
                            <input type="submit" value="Подробнее" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                        @using (Html.BeginForm("Delete", "Classes", new { id = Model.Classes[i].Id }, FormMethod.Post))
                        {
                            <input type="submit" value="Удалить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
</script>
<script type="text/javascript">
    $(function () {
            $("#IncrementYear").click(function (e) {
                if (confirm("Вы уверены?")) {
                    $("#incrementyearform").submit();
                }
            });
        });
</script>

SchoolWebSite2/SchoolWebSite2/Views/Classes/List.cshtml
@model IEnumerable<SchoolWebSite2.Models.Class>


<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>Список классов</h2>
        @Html.AntiForgeryToken()
        <div class="form-horizontal main-container">
            <div class="main-content">
                @foreach (var cl in Model)
                {
                    <div style="display:flex;flex-direction:row;width:400px;">
                        <div style="margin:10px 0;"> @cl.FullName </div>
                        @using (Html.BeginForm("Details", "Classes", new { id = cl.Id }, FormMethod.Get))
                        {
                            <input type="submit" value="Подробнее" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>