SchoolWebSite2/SchoolWebSite2/Models/Classroom.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebSite2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classroom
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int SitsCount { get; set; }
        public bool HasComputers { get; set; }
        public bool HasDigitalEquipment { get; set; }
    }
}

SchoolWebSite2/SchoolWebSite2/Controllers/ClassroomsController.cs
using SchoolWebSite2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolWebSite2.Controllers
{
    public class ClassroomsController : Controller
    {
        public ActionResult Index()
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var list = db.Classroom.Select(c => c).OrderBy(c => c.Number).ToList();
            return View(new CreateAndListClassroomModel() { Classrooms = list, NewClassroom = new Classroom() });
        }

        [HttpPost]
        public ActionResult Create(CreateAndListClassroomModel model)
        {
            var db = new SchoolWebsiteDatabaseEntities();

            if (!db.IsClassroomUnique(model.NewClassroom))
            {
                ModelState.AddModelError(string.Empty, "Кабинет с таким номером уже существует!");
            }

            if (ModelState.IsValid)
            {
                db.Classroom.Add(model.NewClassroom);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            var list = db.Classroom.Select(c => c).OrderBy(c => c.Number).ToList();
            return View("Index", new CreateAndListClassroomModel() { Classrooms = list, NewClassroom = model.NewClassroom });
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classroom = db.Classroom.FirstOrDefault(s => s.Id == id);
            db.Classroom.Remove(classroom);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classroom = db.Classroom.First(c => c.Id == id);
            return View(classroom);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            var classroom = db.Classroom.First(c => c.Id == id);
            return View(classroom);
        }

        [HttpPost]
        public ActionResult Edit(Classroom model)
        {
            var db = new SchoolWebsiteDatabaseEntities();
            if (ModelState.IsValid)
            {
                var classroom = db.Classroom.First(c => c.Id == model.Id);
                if (classroom != null)
                {
                    classroom.SitsCount = model.SitsCount;
                    classroom.HasComputers = model.HasComputers;
                    classroom.HasDigitalEquipment = model.HasDigitalEquipment;
                }
                db.SaveChanges();
                return RedirectToAction("Edit", new { id = model.Id });
            }
            return View(model);
        }
    }
}

SchoolWebSite2/SchoolWebSite2/Views/Classrooms/Details.cshtml
@model SchoolWebSite2.Models.Classroom

<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>Кабинет @Model.Number</h2>
        @Html.AntiForgeryToken()
        <div style="display:flex;flex-direction:column;width:100%;flex-wrap:wrap;justify-content:center;">
            <div>
                @Html.LabelFor(model => model.SitsCount, htmlAttributes: new { @class = "" })
                <div style="font-size: 20px;margin: 20px 0;">@Html.DisplayFor(model => model.SitsCount)</div>
            </div>
            <div>
                @Html.LabelFor(model => model.HasComputers, htmlAttributes: new { @class = "" })
                <div style="font-size: 20px;margin: 20px 0;">@(Model.HasComputers ? " Да" : " Нет") </div>
            </div>
            <div>
                @Html.LabelFor(model => model.HasDigitalEquipment, htmlAttributes: new { @class = "" })
                <div style="font-size: 20px;margin: 20px 0;">@(Model.HasDigitalEquipment ? " Да" : " Нет") </div>
            </div>
        </div>
    </div>
</div>

SchoolWebSite2/SchoolWebSite2/Views/Classrooms/Edit.cshtml
@model SchoolWebSite2.Models.Classroom

<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .number-input {
        width: 50px;
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }

    input[type="checkbox"]:before{
        width:0px;
        height: 0px;
        display:none;
    }

    input[type="checkbox"]:after{
        width:0px;
        height: 0px;
    }

    .checkbox-input {
        width: 20px;
        height: 20px;
        
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>Кабинет @Model.Number</h2>
        @Html.AntiForgeryToken()

        @using (Html.BeginForm("Edit", "Classrooms", null, FormMethod.Post))
        {
            <div style="display:flex;width:100%;flex-wrap:wrap;justify-content:center;">
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.Number)
                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.SitsCount, htmlAttributes: new { @class = "" })
                    @Html.EditorFor(model => model.SitsCount, new { htmlAttributes = new { @class = "form-control code-input", @min = "1", @max = "100" } })
                </div>
                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.HasComputers, htmlAttributes: new { @class = "" })
                    @Html.EditorFor(model => model.HasComputers, new { htmlAttributes = new { @class = "checkbox-input" } })
                    @Html.LabelFor(model => model.HasDigitalEquipment, htmlAttributes: new { @class = "" })
                    @Html.EditorFor(model => model.HasDigitalEquipment, new { htmlAttributes = new { @class = "checkbox-input" } })
                </div>
                <input type="submit" value="Сохранить" class="btn btn-default" style="margin:10px 0; width:150px;" />
            </div>
            @Html.ValidationMessageFor(model => model.SitsCount, "", new { @class = "text-danger" })
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        }
    </div>
</div>

SchoolWebSite2/SchoolWebSite2/Views/Classrooms/Index.cshtml
@model SchoolWebSite2.Models.CreateAndListClassroomModel


<style>
    .options {
        width: 20%;
        background-color: aliceblue;
    }

    .main-part {
        width: 60%;
        text-align: center;
        margin: 20px 10%;
    }

    .main-container {
        display: flex;
        flex-wrap: wrap;
    }

    label, .input-font-size {
        font-size: 20px;
        margin: 0 20px;
        padding-top: 6px;
    }

    .main-content {
        margin: 20px 28%;
        font-size: 20px;
    }

    .lesson-number {
        font-size: 20px;
        padding-top: 8px;
    }

    .checkbox-input {
        width: 20px;
        height: 20px;
        
    }

    .code-input {
        width: 150px;
    }

    .class-teacher-input {
        width: 60%;
    }

    input[type="checkbox"]:before{
        width:0px;
        height: 0px;
        display:none;
    }

    input[type="checkbox"]:after{
        width:0px;
        height: 0px;
    }
</style>

<div class="main-container">
    <div class="options">
        @Html.Partial("UserOptions")
    </div>
    <div class="main-part">
        <h2>Редактирование кабинетов</h2>
        @Html.AntiForgeryToken()

        @using (Html.BeginForm("Create", "Classrooms", null, FormMethod.Post))
        {
            <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;">
                @Html.LabelFor(model => model.NewClassroom.Number, htmlAttributes: new { @class = "" })
                @Html.EditorFor(model => model.NewClassroom.Number, new { htmlAttributes = new { @class = "form-control code-input", @min = "1", @max = "9999" } })
                @Html.LabelFor(model => model.NewClassroom.SitsCount, htmlAttributes: new { @class = "" })
                @Html.EditorFor(model => model.NewClassroom.SitsCount, new { htmlAttributes = new { @class = "form-control code-input", @min = "1", @max = "100" } })
                <div style="display:flex;flex-direction:row;width:100%;flex-wrap:wrap;justify-content:center;margin:10px 0;">
                    @Html.LabelFor(model => model.NewClassroom.HasComputers, htmlAttributes: new { @class = "" })
                    @Html.EditorFor(model => model.NewClassroom.HasComputers, new { htmlAttributes = new { @class = "checkbox-input" } })
                    @Html.LabelFor(model => model.NewClassroom.HasDigitalEquipment, htmlAttributes: new { @class = "" })
                    @Html.EditorFor(model => model.NewClassroom.HasDigitalEquipment, new { htmlAttributes = new { @class = "checkbox-input" } })
                </div>
                <input type="submit" value="Добавить" class="btn btn-default" style="margin:10px 0;" />
            </div>
            @Html.ValidationMessageFor(model => model.NewClassroom.Number, "", new { @class = "text-danger" })
            @Html.ValidationMessageFor(model => model.NewClassroom.SitsCount, "", new { @class = "text-danger" })
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        }

        <div class="form-horizontal main-container">
            <div class="main-content">
                @for (int i = 0; i < Model.Classrooms.Count(); i++)
                {
                    <div style="display:flex;flex-direction:row;width:600px;">
                        <div style="margin:10px 0;"> Кабинет @Model.Classrooms[i].Number </div>
                        @using (Html.BeginForm("Edit", "Classrooms", new { id = Model.Classrooms[i].Id }, FormMethod.Get))
                        {
                            <input type="submit" value="Изменить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                        @using (Html.BeginForm("Details", "Classrooms", new { id = Model.Classrooms[i].Id }, FormMethod.Get))
                        {
                            <input type="submit" value="Подробнее" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                        @using (Html.BeginForm("Delete", "Classrooms", new { id = Model.Classrooms[i].Id }, FormMethod.Post))
                        {
                            <input type="submit" value="Удалить" class="btn btn-default" style="margin-left:auto;margin:10px 10px;" />
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>